var shujvyuan = {
  first: function() {
    var LAreaData = [{
      'region': '京',
      'add': '京'
    }, {
      'region': '津',
      'add': '津'
    }, {
      'region': '冀',
      'add': '冀'
    }, {
      'region': '晋',
      'add': '晋'
    }, {
      'region': '蒙',
      'add': '蒙'
    }, {
      'region': '辽',
      'add': '辽'
    }, {
      'region': '吉',
      'add': '吉'
    }, {
      'region': '黑',
      'add': '黑'
    }, {
      'region': '沪',
      'add': '沪'
    }, {
      'region': '苏',
      'add': '苏'
    }, {
      'region': '浙',
      'add': '浙'
    }, {
      'region': '皖',
      'add': '皖'
    }, {
      'region': '闽',
      'add': '闽'
    }, {
      'region': '赣',
      'add': '赣'
    }, {
      'region': '鲁',
      'add': '鲁'
    }, {
      'region': '豫',
      'add': '豫'
    }, {
      'region': '鄂',
      'add': '鄂'
    }, {
      'region': '湘',
      'add': '湘'
    }, {
      'region': '粤',
      'add': '粤'
    }, {
      'region': '桂',
      'add': '桂'
    }, {
      'region': '琼',
      'add': '琼'
    }, {
      'region': '渝',
      'add': '渝'
    }, {
      'region': '川',
      'add': '川'
    }, {
      'region': '贵',
      'add': '贵'
    }, {
      'region': '云',
      'add': '云'
    }, {
      'region': '藏',
      'add': '藏'
    }, {
      'region': '陕',
      'add': '陕'
    }, {
      'region': '甘',
      'add': '甘'
    }, {
      'region': '青',
      'add': '青'
    }, {
      'region': '宁',
      'add': '宁'
    }, {
      'region': '新',
      'add': '新'
    }, {
      'region': '台',
      'add': '台'
    }, {
      'region': '港',
      'add': '港'
    }, {
      'region': '澳',
      'add': '澳'
    }]
    return LAreaData
  }
}
export {
  shujvyuan
}
